### ISSUE TITLE
sysv init script status is not idempotent

### ISSUE THREAD

**Issue by andyshinn** [mimacom/ansible-role-bamboo#5] opened 2018-03-12 17:51 UTC
You can tag this as help wanted and bug. I'll try to take a look at it the next time I use the role (or if someone gets to it before me). The script was something I made from bits of other sysv init scripts and it is possible that I got this part wrong. I didn't actually notice if it was idempotent or not when I used it for my environment.

**Comment by stromvirvel** [comment] 2018-03-12 22:18
I fixed it with this commit:
https://github.com/mimacom/ansible-role-bamboo/commit/f40be442651abe2559fd5d6920a969eabeeaf84f

The non-idempotence was caused by starting the service (as task) and then restarting the service (as handler). When removing the task "start service" it seems fixed. I'll leave this issue if you want to do further investigation. Otherwise tell me to close it. On the other hand, I'm wondering if the same issue applies to a current Ubuntu version with systemd.

**Closed as completed** 2020-01-04 13:21 UTC
Labels: bug, help wanted
